/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MemberPanel: typeof import('./src/components/MemberPanel.vue')['default']
    MyUiAvatar: typeof import('./src/components/base_ui/MyUiAvatar.vue')['default']
    MyUiBack: typeof import('./src/components/base_ui/MyUiBack.vue')['default']
    MyUiInfoRow: typeof import('./src/components/base_ui/MyUiInfoRow.vue')['default']
    MyUiMenu: typeof import('./src/components/base_ui/MyUiMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/base_ui/SvgIcon.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSpace: typeof import('vant/es')['Space']
    VanTag: typeof import('vant/es')['Tag']
  }
}
